name: I18n CI

on:
  push:
    paths:
    - '**/*.po'
  pull_request:
    paths:
    - '**/*.po'

jobs:
  pofiles:
    name: Translation checks
    runs-on: sid

    steps:
    - uses: actions/checkout@v2

    - name: Installing tools
      run: sudo apt-get install gettext

    - name: Checking .po files
      run: |
        for po in po/*.po docs/man/po/*.po; do
          msgfmt --check --statistics --verbose $po
        done
